"""
Django settings for blog project. 20-02-2023
re 21-05-23
Generated by 'django-admin startproject' using Django 4.1.7.

"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

SECRET_KEY = "django-insecure-xv!!m$c0oloj933db=*%i0ak2hv&@c4qfuczyi()knrme3u1a+"
DEBUG = True
ALLOWED_HOSTS = []

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Packages
    "taggit",
    # "debug_toolbar",
    # Local
    "blog_app.apps.BlogAppConfig",
    # "django.contrib.sites",
    # "django.contrib.sitemaps",
    # "django.contrib.postgres",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # ME : BASE_DIR, 'templates'
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"

# DEBUG_TOOLBAR_PANELS = [
#     "debug_toolbar.panels.headers.HeadersPanel",  # 5
#     "debug_toolbar.panels.request.RequestPanel",  # 6
#     "debug_toolbar.panels.sql.SQLPanel",  # 7
#     "debug_toolbar.panels.versions.VersionsPanel",  # 2
#     "debug_toolbar.panels.settings.SettingsPanel",  # 4
#     # 'debug_toolbar.panels.timer.TimerPanel', # 3
#     # 'debug_toolbar.panels.history.HistoryPanel',    # default order 1
#     # 'debug_toolbar.panels.staticfiles.StaticFilesPanel', # 8
#     # 'debug_toolbar.panels.templates.TemplatesPanel', # 9
#     # 'debug_toolbar.panels.cache.CachePanel', #10
#     # 'debug_toolbar.panels.signals.SignalsPanel', # 11
#     # 'debug_toolbar.panels.redirects.RedirectsPanel', # 12
#     # 'debug_toolbar.panels.profiling.ProfilingPanel', # 13
# ]
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'blogbyex',
#         'USER': 'postgres',
#         'PASSWORD': 'bismillah',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"  # Not working / GET /static/%20css/blog.css HTTP/1.1" 404 1800


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

INTERNAL_IPS = [
    # ... Needed for Dj. debug tool.
    "127.0.0.1",
    # ...
]


"""
0F4C81  Blue
BFD0CA Beige 
"""
